version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-local
    ports:
      - "27019:27017"  
    networks:
      - discovery-network
    volumes:
      - mongodb_data:/data/db  # Persistência dos dados

  discovery-service:
    build: .
    container_name: discovery-service
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb-local:27017  
    ports:
      - "8088:8088"
    networks:
      - discovery-network
    command: npm start
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app

networks:
  discovery-network:
    driver: bridge

volumes:
  mongodb_data:
